// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jackc/pgx/v5/pgxpool"
	"net/http"
	"server/internal/api"
	"server/internal/api/router"
	"server/internal/application"
	user2 "server/internal/auth/user"
	"server/internal/config"
	"server/internal/connection"
	"server/internal/database"
	"server/internal/user"
)

// Injectors from wire.go:

func InitializeApp() *App {
	applicationConfig := config.LoadConfig()
	pool := database.New(applicationConfig)
	userRepository := user.NewUserRepository(pool)
	userController := user.NewUserController(userRepository)
	userDepsContainer := user.NewUserDepsContainer(userRepository, userController)
	applicationRepository := application.NewApplicationRepository(pool)
	applicationController := application.NewApplicationController(applicationRepository)
	applicationDepsContainer := application.NewApplicationDepsContainer(applicationRepository, applicationController)
	connectionRepository := connection.NewConnectionRepository(pool)
	connectionController := connection.NewConnectionController(connectionRepository)
	tokenRepository := user2.NewTokenRepository(pool)
	userAuthService := user2.NewUserAuthService(applicationConfig, userRepository, tokenRepository)
	connectionDepsContainer := connection.NewConnectionDepsContainer(connectionRepository, connectionController, userAuthService)
	userAuthController := user2.NewUserAuthController(applicationConfig, userAuthService, tokenRepository)
	userAuthDepsContainer := user2.NewUserAuthDepsContainer(tokenRepository, userAuthService, userAuthController)
	app := NewApp(applicationConfig, userDepsContainer, applicationDepsContainer, connectionDepsContainer, userAuthDepsContainer, pool)
	return app
}

// wire.go:

type App struct {
	Config          *config.ApplicationConfig
	UserDeps        *user.UserDepsContainer
	ApplicationDeps *application.ApplicationDepsContainer
	ConnectionDeps  *connection.ConnectionDepsContainer
	UserAuthDeps    *user2.UserAuthDepsContainer
	Database        *pgxpool.Pool
	Api             *http.Server
}

func NewApp(config2 *config.ApplicationConfig,
	userDeps *user.UserDepsContainer,
	applicationDeps *application.ApplicationDepsContainer,
	connectionDeps *connection.ConnectionDepsContainer,
	userAuthDeps *user2.UserAuthDepsContainer,
	db *pgxpool.Pool,
) *App {
	r := router.New()
	r.Group(userDeps.RegisterRoutes(r))
	r.Group(applicationDeps.RegisterRoutes(r))
	r.Group(connectionDeps.RegisterRoutes(r))
	r.Group(userAuthDeps.RegisterRoutes(r))
	api2 := api.New(config2, r)

	return &App{
		Config:          config2,
		UserDeps:        userDeps,
		ApplicationDeps: applicationDeps,
		ConnectionDeps:  connectionDeps,
		UserAuthDeps:    userAuthDeps,
		Database:        db,
		Api:             api2,
	}
}
