// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jackc/pgx/v5/pgxpool"
	"net/http"
	api5 "server/internal/api"
	"server/internal/api/router"
	"server/internal/config"
	"server/internal/database"
	"server/internal/domain/application"
	api2 "server/internal/domain/application/api"
	repository2 "server/internal/domain/application/repository"
	user2 "server/internal/domain/auth/user"
	api4 "server/internal/domain/auth/user/api"
	repository4 "server/internal/domain/auth/user/repository"
	"server/internal/domain/auth/user/service"
	"server/internal/domain/connection"
	api3 "server/internal/domain/connection/api"
	repository3 "server/internal/domain/connection/repository"
	"server/internal/domain/user"
	"server/internal/domain/user/api"
	"server/internal/domain/user/repository"
)

// Injectors from wire.go:

func InitializeApp() *App {
	applicationConfig := config.LoadConfig()
	pool := database.New(applicationConfig)
	userRepository := repository.NewUserRepository(pool)
	userController := api.NewUserController(userRepository)
	userDepsContainer := user.NewUserDepsContainer(userRepository, userController)
	applicationRepository := repository2.NewApplicationRepository(pool)
	applicationController := api2.NewApplicationController(applicationRepository)
	applicationDepsContainer := application.NewApplicationDepsContainer(applicationRepository, applicationController)
	connectionRepository := repository3.NewConnectionRepository(pool)
	connectionController := api3.NewConnectionController(connectionRepository)
	tokenRepository := repository4.NewTokenRepository(pool)
	userAuthService := service.NewUserAuthService(applicationConfig, userRepository, tokenRepository)
	connectionDepsContainer := connection.NewConnectionDepsContainer(connectionRepository, connectionController, userAuthService)
	userAuthController := api4.NewUserAuthController(applicationConfig, userAuthService, tokenRepository)
	userAuthDepsContainer := user2.NewUserAuthDepsContainer(tokenRepository, userAuthService, userAuthController)
	app := NewApp(applicationConfig, userDepsContainer, applicationDepsContainer, connectionDepsContainer, userAuthDepsContainer, pool)
	return app
}

// wire.go:

type App struct {
	Config          *config.ApplicationConfig
	UserDeps        *user.UserDepsContainer
	ApplicationDeps *application.ApplicationDepsContainer
	ConnectionDeps  *connection.ConnectionDepsContainer
	UserAuthDeps    *user2.UserAuthDepsContainer
	Database        *pgxpool.Pool
	Api             *http.Server
}

func NewApp(config2 *config.ApplicationConfig,
	userDeps *user.UserDepsContainer,
	applicationDeps *application.ApplicationDepsContainer,
	connectionDeps *connection.ConnectionDepsContainer,
	userAuthDeps *user2.UserAuthDepsContainer,
	db *pgxpool.Pool,
) *App {
	r := router.New()
	r.Group(userDeps.RegisterRoutes(r))
	r.Group(applicationDeps.RegisterRoutes(r))
	r.Group(connectionDeps.RegisterRoutes(r))
	r.Group(userAuthDeps.RegisterRoutes(r))
	api6 := api5.New(config2, r)

	return &App{
		Config:          config2,
		UserDeps:        userDeps,
		ApplicationDeps: applicationDeps,
		ConnectionDeps:  connectionDeps,
		UserAuthDeps:    userAuthDeps,
		Database:        db,
		Api:             api6,
	}
}
